name: Deploy Static Website to Alibaba ECS

on:
  push:
    branches:
      - main  # Trigger pipeline saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Gunakan runner Ubuntu

    steps:
      # Step 1: Checkout code dari repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install rsync untuk transfer file
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # Step 3: Deploy file ke ECS menggunakan rsync
      - name: Deploy to Alibaba ECS
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }}" ./ root@${{ secrets.ECS_IP }}:/var/www/mywebsite/runningCICD
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.ECS_IP }} "sudo systemctl restart nginx"